function build_mavlinkMST_ArucoCamera
%BUILD_MAVLINKMST_ARUCOCAMERA Rebuild the edited model from mavlinkMST.slx.

    projectFolder = fileparts(mfilename('fullpath'));
    addpath(projectFolder);
    aruco_camera_config;
    sourceFile = fullfile(projectFolder, 'mavlinkMST.slx');
    outputFile = fullfile(projectFolder, 'mavlinkMST_ArucoCamera.slx');
    modelName = 'mavlinkMST_ArucoCamera';

    if bdIsLoaded(modelName)
        close_system(modelName, 0);
    end
    copyfile(sourceFile, outputFile, 'f');
    load_system(outputFile);

    % Make the helper class and marker configuration available when the model
    % is opened directly from Finder or from another MATLAB working folder.
    preload = [ ...
        "modelFile = get_param(bdroot,'FileName'); " ...
        "if ~isempty(modelFile), addpath(fileparts(modelFile)); end; " ...
        "aruco_camera_config;"];
    set_param(modelName, 'PreLoadFcn', char(preload));
    init = [ ...
        "aruco_camera_config; " ...
        "set_param([bdroot '/ArUco Landing Camera']," ...
        "'MarkerFile',markerImageFile); " ...
        "set_param([bdroot '/RGB Frames to Python']," ...
        "'Host',cameraFrameHost);"];
    set_param(modelName, 'InitFcn', char(init));

    receiver = [modelName '/TCP//IP Receive'];
    set_param(receiver, 'DataSize', '256', 'SampleTime', '0.02');

    % Keep the existing position decoder and add an attitude-quaternion
    % decoder. Both inspect the same stream of MAVLink bytes.
    load_system('uavmavlinklib');
    attitudeDecoder = [modelName '/ATTITUDE_QUATERNION Deserializer'];
    add_block('uavmavlinklib/MAVLink Deserializer', attitudeDecoder, ...
        'Position', [300 510 515 621]);
    % The R2025b message-type mask callback is UI-only and errors in batch
    % mode. Make this copied decoder standalone before changing its type.
    set_param(attitudeDecoder, 'LinkStatus', 'none');
    decoderMask = Simulink.Mask.get(attitudeDecoder);
    messageTypeParameter = decoderMask.getParameter('messageType');
    messageTypeCallback = messageTypeParameter.Callback;
    messageTypeParameter.Callback = '';
    set_param(attitudeDecoder, 'messageType', 'ATTITUDE_QUATERNION');
    messageTypeParameter.Callback = messageTypeCallback;

    attitudeSelector = [modelName '/Quaternion Selector'];
    add_block([modelName '/Bus Selector'], attitudeSelector, ...
        'Position', [570 525 575 615]);
    set_param(attitudeSelector, 'OutputSignals', ...
        'Payload.q1,Payload.q2,Payload.q3,Payload.q4');

    camera = [modelName '/ArUco Landing Camera'];
    add_block('simulink/User-Defined Functions/MATLAB System', camera, ...
        'Position', [760 235 965 485]);
    set_param(camera, 'System', 'ArucoLandingCamera');
    set_param(camera, ...
        'MarkerFile', markerImageFile, ...
        'MarkerSizeMeters', 'markerSizeMeters', ...
        'MarkerNorthMeters', 'markerNorthMeters', ...
        'MarkerEastMeters', 'markerEastMeters', ...
        'MarkerYawDegrees', 'markerYawDegrees', ...
        'GroundDownMeters', 'groundDownMeters', ...
        'HorizontalFovDegrees', 'cameraHorizontalFovDegrees', ...
        'ImageWidth', 'cameraImageWidth', ...
        'ImageHeight', 'cameraImageHeight', ...
        'FramePeriodSeconds', 'cameraFramePeriodSeconds');

    load_system('visionsinks');
    viewer = [modelName '/Simulated Camera View'];
    add_block('visionsinks/Video Viewer', viewer, ...
        'Position', [1060 315 1195 385]);
    set_param(viewer, 'OpenAtMdlStart', 'on', ...
        'imagePorts', 'One multidimensional signal');

    frameServer = [modelName '/RGB Frames to Python'];
    add_block('simulink/User-Defined Functions/MATLAB System', frameServer, ...
        'Position', [1060 445 1195 515]);
    set_param(frameServer, 'System', 'ArucoFrameServer');
    set_param(frameServer, 'Host', cameraFrameHost, ...
        'Port', 'cameraFramePort');

    add_line(modelName, 'TCP//IP Receive/1', ...
        'ATTITUDE_QUATERNION Deserializer/1', 'autorouting', 'on');
    add_line(modelName, 'ATTITUDE_QUATERNION Deserializer/2', ...
        'Quaternion Selector/1', 'autorouting', 'on');

    for port = 1:3
        add_line(modelName, sprintf('Bus Selector/%d', port), ...
            sprintf('ArUco Landing Camera/%d', port), 'autorouting', 'on');
    end
    for port = 1:4
        add_line(modelName, sprintf('Quaternion Selector/%d', port), ...
            sprintf('ArUco Landing Camera/%d', port + 3), 'autorouting', 'on');
    end
    add_line(modelName, 'ArUco Landing Camera/1', ...
        'Simulated Camera View/1', 'autorouting', 'on');
    add_line(modelName, 'ArUco Landing Camera/1', ...
        'RGB Frames to Python/1', 'autorouting', 'on');

    % Request LOCAL_POSITION_NED (32) and ATTITUDE_QUATERNION (31) at 20 Hz.
    % These are two complete MAVLink 2 COMMAND_LONG packets.
    requestBytes = uint8([ ...
        253 33 0 0 0 255 190 76 0 0 0 0 0 66 0 80 67 71 0 0 0 0 0 ...
        0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 255 1 1 1 0 74 217 ...
        253 33 0 0 1 255 190 76 0 0 0 0 248 65 0 80 67 71 0 0 0 0 0 ...
        0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 255 1 1 1 0 48 178]);
    requestSubsystem = [modelName '/Request LOCAL_POSITION_NED'];
    set_param(requestSubsystem, 'Name', 'Request pose messages');
    requestSubsystem = [modelName '/Request pose messages'];
    commandBlock = [requestSubsystem '/SET_MESSAGE_INTERVAL command'];
    set_param(commandBlock, 'Name', 'Request position and attitude at 20 Hz');
    commandBlock = [requestSubsystem '/Request position and attitude at 20 Hz'];
    set_param(commandBlock, 'Value', ['uint8(' mat2str(requestBytes) ')']);
    set_param([modelName '/Request every 2 s'], 'Name', ...
        'Request pose every 2 s', 'Period', '2');

    note = Simulink.Annotation(modelName, sprintf([ ...
        'ARUCO CAMERA CONFIGURATION\n' ...
        'Edit aruco_camera_config.m to change the marker image, marker pose, ' ...
        'physical size, field of view, or resolution.\n' ...
        'The camera is rigidly mounted downward in the drone body frame.\n' ...
        'RGB frames are also published to the Python precision-landing bridge.']));
    note.Position = [755 80 1195 165];
    note.FontSize = 11;

    set_param(modelName, 'Location', [50 50 1450 850]);
    set_param(modelName, 'ZoomFactor', 'FitSystem');
    set_param(modelName, 'SimulationCommand', 'update');
    save_system(modelName, outputFile);
    close_system(modelName, 0);
    fprintf('Built %s\n', outputFile);
end
